### ISSUE TITLE
[USER ISSUE] Workers failing to upload results / going offline

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#1483]
**Describe the bug**

a lot of my jobs seem to be showing their state as `worker_offline` after (seemingly successful) completion...all the expected output files are there, and there are no errors in stdout or stderr. Looking at the logs of the worker, it seems like they get stuck uploading results. For instance, bundle https://worksheets.codalab.org/bundles/0x9f6d484780bf4cbea417ce2b1d7b771f and the worker log output `2019-10-08 08:18:19,377 Uploading results for run with UUID 0x9f6d484780bf4cbea417ce2b1d7b771f` (even though the results are super small, and should not take that much time to upload...)

**Codalab Information**
- *Your username*: nfliu
- *UUID of worksheet where problem occurred*: 0xa49368ebd6e64154b683ed8812634ae9
- *UUID of problem bundle (please don't delete)*: 0x9f6d484780bf4cbea417ce2b1d7b771f
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*: Mac OS Mojave
 - *Codalab CLI Version (if on CLI)*: 0.4.3
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. I think you should be reproduce if you just run a bundle? I have bundles in other worksheets that show `worker_offline` and don't even upload their results (including stderr/stdout).

**Expected behavior**
Jobs succeed

**Comment by nelson-liu** [comment]
to update: it seems like sometimes the results are properly uploaded (annoying, but manageable, since I can treat the run as succeeding), and sometimes the results are not uploaded (run is as good as failing). I haven't been able to really discern the factors that decide whether the upload succeeds and when it fails.

**Comment by bkgoksel** [comment]
This was happening on experimental AWS batch runs too, and it was actually
due to Docker network name conflicts. Should be fixed on master now after
the worker-manager PR got merged.

**Comment by nelson-liu** [comment]
Dumb question: could I solve this by installing the codalab cli from master? or does something need to be updated on worksheets.codalab.org as well? Sorry, still not entirely sure how they interact.

**Comment by percyliang** [comment]
If you're using nlp-cl-worker, then this is still using codalab 0.3.3.
/u/nlp/data/codalab/cl-venv needs to be upgraded.

**Comment by nelson-liu** [comment]
Ok, I upgraded the worker locally, and runs have started passing. Thanks all for the help! Note that nlp-cl-worker remains on 0.3.3 --- I'm not entirely how to setup the shared venv that backs nlp-cl-worker , since it has to be upgraded to python 3.x as well.
