### ISSUE TITLE
Can't insert a new text item after a records row

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2249]
To test:

```
% display record
[run run-echo : echo "HU"]{0xe7b2c91e5d944f5dbcbe5216efc0162c}
[run run-echo : echo "HU"]{0xb9a6ced6ea724d239e405e1938fadea7}
[run run-echo : echo "A"]{0x87e92d44d8c442f29d0d78e72fa7a8a1}
[run run-echo : echo "A"]{0xab5da56231014e36935e2cef4bca767e}
```

**Comment by percyliang** [comment]
@epicfaace is this fixed by your recent changes?

**Comment by epicfaace** [comment]
#2190 fixed this issue for non-records rows, but it appears that the issue still persists for records rows. We merged #2190 anyway because it at least fixed the majority of scenarios.
