### ISSUE TITLE
Unable to connect to worksheets using the command line interface

### ISSUE THREAD

**Issue by mk351** [codalab/codalab-worksheets#257]
Hi,

I need to add a user to a group, but I am unable to do so since the website's security certificate expired yesterday. The cli refuses to work, and I don't think there is any way to do this using the web interface. This is quite urgent, since it is linked with a live competition on codalab. Would be great if you could fix this today.

Thanks

**Comment by percyliang** [comment]
The certificates are updated, so everything should be working now.

**Comment by mk351** [comment]
Thanks. This is working now on any system where I install the cli anew. But still isn't working on my system, where I had installed the CLI previously. Do I need to make any changes in the configuration?

**Comment by kashizui** [comment]
You may try removing the virtualenv (should be in `path/to/codalab-cli/venv`) and then rerunning `setup.sh`. I heard that someone else had resolved this by switching to a different environment.

**Comment by mk351** [comment]
Thanks @kashizui, but I tried this, as well as a fresh install of codalab-cli, and neither worked

**Comment by percyliang** [comment]
This should be fixed.  Please reopen if there are still issues @mk351
