### ISSUE TITLE
Bundle failed to run

### ISSUE THREAD

**Issue by zyds** [codalab/codalab-worksheets#445]
Hi, 
    I have found that many people have recently raised the issue that the budle cannot download dependencies, and I have encountered this problem. 
    I want to know if this is a problem with the entire platform. If it is not the problem of the entire platform, is there any good way to avoid it?

**Comment by bkgoksel** [comment]
Hi,
There were some wider issues earlier but we have published fixes for them last week. Can you share details of any bundles that had issues so we may look into it?

**Comment by zyds** [comment]
Thanks for your reply.
When I uploaded all the files again in my classmate's account, the problem seemed to disappear. But in my account, this problem still exists (probably because I didn't re-upload files). The bundle UUID is 0xce5ac443610245659194d8a2c6e17445.

**Comment by percyliang** [comment]
There have been a lot of changes to the worker system.  Closing for now, but please re-open if it's still outstanding.
